# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Fetching COVID-19 data daily in Malaysia

on:
  schedule:
    - cron: '0 18 * * * # run at 6pm UTC everyday
  workflow_dispatch:
    branches: [ master ]
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        cd ./.github/workflows/
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Get the number of infecteds by states from a blog of Health Director of Malaysia
      run: |
        cd ./
        python dataFromHealthDirectorBlog.py
        
    - name: Get the number of nationwide total from The Star Online
      run: |
        cd ./
        python dataFromStarOnline.py
        
    - name: Export the above results to GitHub repository
      env:
        GIT_OWNER_EMAIL: ${{ secrets.GIT_OWNER_EMAIL }}
        PUSH_TOKEN: ${{ secrets.PUSH_TOKEN }}
      run: |
        git config user.email "$GIT_OWNER_EMAIL"
        git config user.name "ukkdosm"
        git add -A
          git commit -m "update data" -a
          
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main  
